### ISSUE TITLE
Unexpected exception[UnsatisfiedLinkError: Failed to load Brotli native library]

### ISSUE THREAD

**Issue by henricook** [guardian/play-brotli-filter#11]
I'm working to solve this, but thought I'd post here in the meantime in case it's familiar to you.

I have a play project that uses compile time DI (so not play's default dynamic runtime DI) - I mention that because I suspect it's probably related to this error:

```
play.api.UnexpectedException: Unexpected exception[UnsatisfiedLinkError: Failed to load Brotli native library]
	at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:258)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:148)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:95)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:203)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
Caused by: java.lang.UnsatisfiedLinkError: Failed to load Brotli native library
	at play.filters.brotli.loader.BrotliNativeLoader.ensureAvailability(BrotliNativeLoader.java:78)
	at play.filters.brotli.Brotli.ensureAvailability(Brotli.java:69)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:42)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:50)
	at ai.henricook.common.PlayFiltersModule.httpFilters(PlayFiltersModule.scala:29)
	at ai.henricook.common.PlayFiltersModule.httpFilters$(PlayFiltersModule.scala:26)
	at ai.henricook.ApplicationModule.httpFilters(ApplicationModule.scala:195)
	at play.api.BuiltInComponents.httpRequestHandler(Application.scala:316)
	at play.api.BuiltInComponents.httpRequestHandler$(Application.scala:309)
	at play.api.BuiltInComponentsFromContext.httpRequestHandler$lzycompute(ApplicationLoader.scala:228)
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.nio.file.Files.copy(Files.java:3035)
	at play.filters.brotli.loader.BrotliNativeLoader.<clinit>(BrotliNativeLoader.java:47)
	at play.filters.brotli.Brotli.<clinit>(Brotli.java:43)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:42)
	at play.filters.brotli.BrotliFilter.<init>(BrotliFilter.scala:50)
	at ai.henricook.common.PlayFiltersModule.httpFilters(PlayFiltersModule.scala:29)
	at ai.henricook.common.PlayFiltersModule.httpFilters$(PlayFiltersModule.scala:26)
	at ai.henricook.ApplicationModule.httpFilters(ApplicationModule.scala:195)
	at play.api.BuiltInComponents.httpRequestHandler(Application.scala:316)
```

I'm instantiating the file like this:

```scala
new BrotliFilter(
      shouldBrotli = (reqHeader, _) => {
        reqHeader.contentType.exists(cType =>
          List(
            "application/json",
            "text/plain",
          ).contains(cType)
        )
      }
    )
```

and adding it to the list of filters we use for all our other filters (including play default filters) in our class that extends Play's `HttpFiltersComponents`

**Comment by henricook** [comment]
Resolved https://github.com/hyperxpro/Brotli4j/issues/51
