### ISSUE TITLE
Play 2.9.0 Support

### ISSUE THREAD

**Issue by henricook** [guardian/play-brotli-filter#17]
Under Play 2.9 the filter no longer works.

Requests using it end with this error:

```
ncaught error from thread [application-akka.actor.default-dispatcher-8]: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)'
	at play.filters.brotli.BrotliFilter.play$filters$brotli$BrotliFilter$$handleResult(BrotliFilter.scala:92)
	at play.filters.brotli.BrotliFilter$$anon$1.$anonfun$apply$1(BrotliFilter.scala:77)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by henricook** [comment]
https://github.com/guardian/play-brotli-filter/pull/18

**Comment by mchv** [comment]
This should now be addressed by https://github.com/guardian/play-brotli-filter/pull/22

**Comment by henricook** [comment]
Works beautifully, thanks!
